### ISSUE TITLE
Drivers Issue in Ubuntu

### ISSUE THREAD

**Issue by Sami-listens** [Altimis/Scweet#1]
**How can a newbie run it using ubuntu as it shows the following error there (Complete trackback)**

`Traceback (most recent call last):
  File "/home/sami/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './drivers/chromedriver.exe': './drivers/chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "twitter_Scraper.py", line 314, in <module>
    data=scrap(words, to_account, from_account, start_date,max_date,interval,navig,lang, headless, limit,display_type,resume)
  File "twitter_Scraper.py", line 162, in scrap
    driver=init_driver(navig, headless)
  File "twitter_Scraper.py", line 127, in init_driver
    driver = webdriver.Chrome(options=options,executable_path=browser_path)
  File "/home/sami/.local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/sami/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

`

**Comment by Altimis** [comment]
@Sami-listens I made this code for Windows. You need to check your chrome's version and download chromedriver.exe from [here](https://chromedriver.chromium.org/downloads) for linux and drag it to the repository. Then go the the scweet.py and make a change in line 127 in the function ``init_driver`` where you need to replace ``'./drivers/chromedriver.exe'``  by the appropriate path format in linux (I think "\" instead of "/". You can also just download the driver and specify it in your PATH.

**Comment by Sami-listens** [comment]
Thank you @Altimis , I changed the driver path to `'/usr/bin/chromedriver'` and it worked. :)
