### ISSUE TITLE
get_user_follow fails since new chrome version

### ISSUE THREAD

**Issue by PairplaneN** [Altimis/Scweet#113]
Hi,
When scraping followers and followings, I receive the following error (since the update of chrome on my linux pc from version 98.xxx to 99.xxx):

Traceback (most recent call last):
 
  File "~/Scweet/utils.py", line 385, in get_users_follow
    log_in(driver, env, wait=wait)
  File "~/Scweet/utils.py", line 305, in log_in
    email_el = driver.find_element(By.XPATH, email_xpath)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@autocomplete="username"]"}
  (Session info: headless chrome=99.0.4844.51)
Stacktrace:
#0 0x5613b9b24233 <unknown>
#1 0x5613b987a658 <unknown>
#2 0x5613b98b0941 <unknown>
#3 0x5613b98b0b01 <unknown>
#4 0x5613b98e3a34 <unknown>
#5 0x5613b98ce06d <unknown>
#6 0x5613b98e17bb <unknown>
#7 0x5613b98cdf33 <unknown>
#8 0x5613b98a3c8a <unknown>
#9 0x5613b98a4d55 <unknown>
#10 0x5613b9b54c5d <unknown>
#11 0x5613b9b6e17e <unknown>
#12 0x5613b9b569c5 <unknown>
#13 0x5613b9b6ec95 <unknown>
#14 0x5613b9b4a900 <unknown>
#15 0x5613b9b89e28 <unknown>
#16 0x5613b9b89fa8 <unknown>
#17 0x5613b9ba36ad <unknown>
#18 0x7f7219033609 <unknown>

Thank you for looking into this problem.

**Comment by rosscg** [comment]
I've added Firefox support in the fork here:
https://github.com/rosscg/Scweet/tree/7aadb838eb5ff1db34f0eb1b5af0576c0a8a28bc

It's set as the default in get_users_follow so it can run without changing anything else.

**Comment by ShoufaChen** [comment]
Hi, @rosscg 

Thanks for your contribution. I found that you import 
```
from .const import get_username, get_password, get_email, get_geckdriver_path
```

but `.const` does not contains `get_geckdriver_path`.

Could you help me?

**Comment by rosscg** [comment]
@ShoufaChen Yes that's an import I replaced (so shouldn't be there). I've updated the repo so either use the latest on my fork or just remove ", get_geckdriver_path" from that line in utils.py

**Comment by ShoufaChen** [comment]
Thank you @rosscg.

**Comment by PairplaneN** [comment]
Thank you @rosscg and @ShoufaChen, it's working again.
