### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by MHketbi** [Altimis/Scweet#129]
i keep getting this error and i dont know why:

> C:\Scweet>python Example.py
Scraping on headless mode.
Traceback (most recent call last):
  File "C:\Scweet\Example.py", line 34, in <module>
    following = get_users_following(users=users, env=env_path, verbose=0, headless=True, wait=2, limit=50, file_path=".txt")
  File "C:\Scweet\Scweet\user.py", line 112, in get_users_following
    following = utils.get_users_follow(users, headless, env, "following", verbose, wait=wait, limit=limit)
  File "C:\Scweet\Scweet\utils.py", line 324, in get_users_follow
    driver = init_driver(headless=headless, env=env, firefox=True)
  File "C:\Scweet\Scweet\utils.py", line 151, in init_driver
    driver = webdriver.Firefox(options=options, executable_path=driver_path)
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 172, in __init__
    self.service.start()
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1378, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 561, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

this is the code 
```from Scweet.scweet import scrape
from Scweet.user import get_user_information, get_users_following, get_users_followers

users = ['@xyz']

env_path = ".env"

following = get_users_following(users=users, env=env_path, verbose=0, headless=True, wait=2, limit=50, file_path=".txt")

followers = get_users_followers(users=users, env=env_path, verbose=0, headless=True, wait=1, limit=50, file_path=".txt")```

**Comment by Simon006** [comment]
Have you solved your problem？
