### ISSUE TITLE
Cannot run the module

### ISSUE THREAD

**Issue by unkn0wn95** [Altimis/Scweet#19]
mkdir: cannot create directory '/run/user/0': Permission denied
Scraping on headless mode.
Traceback (most recent call last):
  File "scweet.py", line 155, in <module>
    data = scrap(start_date, max_date, words, to_account, from_account, interval, navig, lang, headless, limit,
  File "scweet.py", line 22, in scrap
    driver = init_driver(navig, headless, proxy)
  File "/home/wew/Pictures/Scweet/Scweet/utils.py", line 201, in init_driver
    driver = webdriver.Chrome(options=options, executable_path=chromedriver_path)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /snap/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by Altimis** [comment]
Are you working on Linux ?

**Comment by unkn0wn95** [comment]
Yes

**Comment by Altimis** [comment]
@unkn0wn95  add these two lines of code : 

`` options.add_argument("--no-sandbox") 
options.add_argument("--disable-dev-shm-usage")
``
in utils.py in the line 196.

**Comment by unkn0wn95** [comment]
Different Error on different user:  

(Run as normal user):
`Traceback (most recent call last):
  File "searchtweet.py", line 4, in <module>
    scrap(start_date="2020-01-01", max_date="2020-01-03", from_account = "realDonaldTrump",interval=1,navig="chrome", headless=True, display_type="Top")
  File "/home/wew/Documents/Scweet/Scweet/scweet.py", line 22, in scrap
    driver = init_driver(navig, headless, proxy)
  File "/home/wew/Documents/Scweet/Scweet/utils.py", line 187, in init_driver
    chromedriver_path = chromedriver_autoinstaller.install()
  File "/usr/local/lib/python3.8/dist-packages/chromedriver_autoinstaller/__init__.py", line 15, in install
    chromedriver_filepath = utils.download_chromedriver(cwd)
  File "/usr/local/lib/python3.8/dist-packages/chromedriver_autoinstaller/utils.py", line 202, in download_chromedriver
    zip_file.extract(chromedriver_filename, chromedriver_dir)
  File "/usr/lib/python3.8/zipfile.py", line 1630, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/lib/python3.8/zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.8/dist-packages/chromedriver_autoinstaller/87/chromedriver'
`
(Run as Super user):
`mkdir: cannot create directory '/run/user/0': Permission denied
Scraping on headless mode.
Traceback (most recent call last):
  File "searchtweet.py", line 4, in <module>
    scrap(start_date="2020-01-01", max_date="2020-01-03", from_account = "realDonaldTrump",interval=1,navig="chrome", headless=True, display_type="Top")
  File "/home/wew/Documents/Scweet/Scweet/scweet.py", line 22, in scrap
    driver = init_driver(navig, headless, proxy)
  File "/home/wew/Documents/Scweet/Scweet/utils.py", line 203, in init_driver
    driver = webdriver.Chrome(options=options, executable_path=chromedriver_path)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist`

**Comment by Altimis** [comment]
Did you add the two lines of code above? I think the problem comes from the chromedriver installation. You can add the options above or install chromedriver manually in their uglt official website.

**Comment by unkn0wn95** [comment]
I already add it like this on line 196:

`options = Options()
        if headless is True:
            print("Scraping on headless mode.")
            options.add_argument('--disable-gpu')
            options.headless = True
        else:  
            options.headless = False
        options.add_argument('log-level=3')
        options.add_argument("--no-sandbox")   
        options.add_argument("--disable-dev-shm-usage")`

**Comment by Altimis** [comment]
Do you know your port number ? if so, add this : 
``options.add_argument("--remote-debugging-port=<port>")

**Comment by unkn0wn95** [comment]
Done add it and it worked .Thank you Bro
