### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by the-data-mogul** [Altimis/Scweet#21]
Hi, I am trying to run the **example script**:
from scweet import scrap
from user import get_user_information, get_following, get_followers

following, followers, join_date, location, website, description = get_user_information("realDonaldTrump")

print('following:'+following+'\nfollowers: '+followers+'\njoin_date: '+join_date+ '\nlocation: ' +location + '\nwebsite: '+website + '\ndescription: '+description)

And am facing the following **issue**:

Traceback (most recent call last):
  File "user_data.py", line 4, in <module>
    following, followers, join_date, location, website, description = get_user_information("realDonaldTrump")
  File "D:\Twitter\Scweet\Scweet\user.py", line 8, in get_user_information
    driver = utils.init_driver(headless=headless)
  File "D:\Twitter\Scweet\Scweet\utils.py", line 187, in init_driver
    chromedriver_path = chromedriver_autoinstaller.install()
  File "D:\Twitter\Scweet\scweet-venv\lib\site-packages\chromedriver_autoinstaller\__init__.py", line 15, in install
    chromedriver_filepath = utils.download_chromedriver(cwd)
  File "D:\Twitter\Scweet\scweet-venv\lib\site-packages\chromedriver_autoinstaller\utils.py", line 166, in download_chromedriver
    chrome_version = get_chrome_version()
  File "D:\Twitter\Scweet\scweet-venv\lib\site-packages\chromedriver_autoinstaller\utils.py", line 117, in get_chrome_version
    version = process.communicate()[0].decode('UTF-8').strip().split()[-1]
IndexError: list index out of range

Please help!! Thank you.

**Comment by Altimis** [comment]
Hi. Do you have chrome installed in your system ?

**Comment by the-data-mogul** [comment]
I had not installed Chrome. What a bummer!! The script works now! Thank you!

**Comment by Altimis** [comment]
@the-data-mogul  Hhahha, it's ok. It heppens.

**Comment by joedsf** [comment]
我安装了chrome，但还是出现了这个问题，请问怎么办

**Comment by joedsf** [comment]
以前可以使用，后来突然不行了
