### ISSUE TITLE
error while running the example.py on docker, why so? And when I run the same file on local, it runs properly, but to fetch 1000 followers/followings it takes 7 to 8 minutes, what can be done to make the process faster?

### ISSUE THREAD

**Issue by purnima110895** [Altimis/Scweet#80]
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=92.0.4515.131)
Any help @Altimis

**Comment by purnima110895** [comment]
Traceback (most recent call last):
  File "scweet_get_relationships.py", line 27, in <module>
    followers = get_users_followers(users=users, env=env_path, verbose=0, headless=True, wait=5,limit=10)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\Scweet\user.py", line 104, in get_users_followers
    with open(file_path, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/myogiadityanath_myogiadityanath_followers.json'

Why getting this error , is there any change in the api, on limit parameter or so?
Please Reply @Altimis

**Comment by purnima110895** [comment]
Please do reply @Altimis, if you have any solution on the above issue.

**Comment by Altimis** [comment]
Regarding the time of retrieving followers/following, there is a wait parameter that controls waiting time between each scroll. Its default value is 2. If you have a good connection, set it to 0.5 or 1 to minimize the time. 
There could be another way to retrieve this data faster, which is scrolling first until the end of the page and then retrieve all data in the element. But it could ban the account that you are using... I'll try this later. Technically speaking, the best way would be to retrieve data from the graph directly, instead of using selenium to retrieve it statically. 
However, I've never tried to use this lib in docker... So I have no idea.

**Comment by purnima110895** [comment]
Can we apply multithreading on this functions, like if mutiple users are trying to fetch the data at the same time with the same account, is it expandable?

**Comment by purnima110895** [comment]
Any help on the above query @Altimis . Please do reply.

**Comment by Altimis** [comment]
> Thanks for the response @Altimis , that docker issue has been resolved. Need one more help -
> Can we apply multithreading on this functions, like if mutiple users are trying to fetch the data at the same time with the same account, is it expandable?
> Please let us know if multithreading can be implemented on this @Altimis .


Can you point out how did you solve the docker problem please ? 
Regarding your suggestion,  As far as I know, it is possible to do multithreading with selenium. So it is possible to retrieve following/followers likewise. Although I havent try it yet.

**Comment by purnima110895** [comment]
> > Thanks for the response @Altimis , that docker issue has been resolved. Need one more help -
> > Can we apply multithreading on this functions, like if mutiple users are trying to fetch the data at the same time with the same account, is it expandable?
> > Please let us know if multithreading can be implemented on this @Altimis .
> 
> Can you point out how did you solve the docker problem please ?
> Regarding your suggestion, As far as I know, it is possible to do multithreading with selenium. So it is possible to retrieve following/followers likewise. Although I havent try it yet.

Tanks for the response @Altimis . Regarding that docker-
Actually we were using microservices and this scweet api and in between we had restapi to call this scweet in the microservice, previously used different containers in docker to run the MS and Scweet api, after alot of efforts, tried resolving running MS and scweet api in same container, it worked out.
